[package]
name = "switchvisor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "A lightweight AArch64 hypervisor core for Nintendo Switch"

[dependencies]
gdbstub.workspace = true
gdbstub_arch.workspace = true

[features]
baremetal = []

[[bin]]
name = "switchvisor"
path = "src/main.rs"
required-features = ["baremetal"]
test = false
bench = false
