[workspace]
members = ["crates/switchvisor", "crates/switchvisor-tool", "crates/switchvisorctl"]
default-members = ["crates/switchvisor", "crates/switchvisor-tool", "crates/switchvisorctl"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "GPL-2.0-only"
repository = "https://github.com/petitstrawberry/switchvisor"
homepage = "https://github.com/petitstrawberry/switchvisor"

[workspace.dependencies]
switchvisor = { version = "0.1.0", path = "crates/switchvisor" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.9"
nusb = "0.2.7"
serialport = { version = "4.10.1", default-features = false, features = ["usbportinfo-interface"] }

[profile.release]
panic = "abort"
overflow-checks = true
