[alias]
check-el2 = "check -p switchvisor-core --target aarch64-unknown-none-softfloat"
build-boot = "build -p switchvisor-boot --features baremetal --target aarch64-unknown-none-softfloat --release"

[target.aarch64-unknown-none-softfloat]
rustflags = ["-C", "target-cpu=cortex-a57", "-C", "target-feature=-neon"]
