[package]
name = "switchvisor-boot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
baremetal = []

[[bin]]
name = "switchvisor-boot"
path = "src/main.rs"
required-features = ["baremetal"]
test = false
bench = false

[dependencies]
switchvisor-core.workspace = true
